apiVersion: v1
kind: Service
metadata:
  name: devboard-frontend-service
  namespace: devboard
spec:
  selector:
    app: frontend-backend
  ports:
    - protocol: TCP
      port: 30080
      targetPort: 4173
      NodePort: 30080
  type: Nodetype 

